spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: dev
    group:

      dev: "dev, datasource"
      prod: "prod, datasource"
  mail:
    host: smtp.gmail.com
    port: 587
    username: shain111414@gmail.com
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000
  data:
    redis:
      port: ${REDIS_PORT}
      host: ${REDIS_HOST}

server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

swagger:
  version: ${SWAGGER_VERSION:0.0.1}
springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /api-docs
    disable-swagger-default-url: true
    display-request-duration: true
    tags-sorter: alpha
    operations-sorter: alpha
    syntax-highlight:
      theme: none
    urls-primary-name: MUSINSAWAGON API DOCS
oauth:
  kakao:
    client-id: 3fbb085f93e4a03ef219e0ed5d59c351
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
jwt:
  expiration_time: 86400000 # 1일
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa