spring:
  config:
    activate:
      on-profile: "dev"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: Asia/Seoul
        format_sql: true
      show-sql: true

  datasource:
    url: jdbc:mysql://112.187.174.132:3306/pricewagon?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maxLifetime: 580000
      maximum-pool-size: 20
      idle-timeout: 30000
      connection-timeout: 30000
      username: hong
      password: 87914859

# 로깅 설정
logging:
  level:
    org:
      springframework:
        security: trace
        web: DEBUG
    hibernate:
      orm:
        jdbc:
          bind: trace


